name: CI/CD Pipeline Postgres

# Desabilita múltiplas execuções da mesma pipeline
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_IMAGE_TAG: latest

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  # Realiza as verificações de pre-commit do dockerfile
  pre-commit:
    name: Executa pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Executa pre-commit
        uses: pre-commit/action@v3.0.1

  build-push:
    name: Build e Push da Imagem Docker
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Repositório Nexus
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}
