name: CI/CD Pipeline Metabase

# Desabilita múltiplas execuções da mesma pipeline
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  # Realiza as verificações de pre-commit do dockerfile
  pre-commit:
    name: Executa pre-commit
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v4

      - name: Copia .env
        run: |
          cp .env.example .env
          cp .env.example stack.env

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Executa pre-commit
        uses: pre-commit/action@v3.0.1
