name: Release Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versão (e.g., v1.2.3)'
        required: true
        type: string
      description:
        description: 'Descrição da release'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hive-metastore

jobs:
  pre_commit_validation:
    name: Executa pre-commit
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v4

      - name: Copia .env
        run: |
          cp .env.example .env
          cp .env.example stack.env

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Executa pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: dockerfilelint --all-files

  build_and_publish:
    name: Build, Push, and Publish
    runs-on: ubuntu-latest
    needs: pre_commit_validation # Depende da validação do Dockerfile
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
          draft: false
          prerelease: false
